# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# ignore all warnings from all dependencies
inhibit_all_warnings!


target 'DisplayTVShows' do
  use_frameworks!

  pod 'SwiftLint'
  pod 'SVProgressHUD'
  pod 'lottie-ios'
  pod 'AlamofireImage'
  pod 'SnapKit'

  target 'DisplayTVShowsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

